from typing import Protocol
from qa_bot.domain.observation import BrowserSnapshot


class BrowserPort(Protocol):
    async def open(self, url: str, *, timeout: float = 30) -> None: ...
    async def observe(self, *, timeout: float) -> BrowserSnapshot: ...
    async def close(self) -> None: ...
