#!/bin/bash
# Reproducible build + deploy of the residential-proxy delivery layer.
#   - cross-compiles the Go client (client/) for Windows/macOS/Linux, embedding dist/tunnel_key
#   - generates the landing page + mac/win installer wrappers into dist/ (all gitignored)
#   - deploys them to the token-gated web dir /var/www/proxy-dist/<token>/
# One-time server setup (NOT here — see README): the `tunnel` SSH user + authorized_keys, the
# nginx proxy.systeam.kz vhost + certbot cert. Re-run this after changing the client or rotating
# the key/token. Requires: go on PATH, dist/tunnel_key + dist/token present.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
D="$HERE/dist"
TOKEN="$(cat "$D/token")"
WEB="/var/www/proxy-dist/$TOKEN"
export GOPATH="${GOPATH:-/tmp/gopath}" GOCACHE="${GOCACHE:-/tmp/gocache}"

echo "== embed key + cross-compile =="
cp "$D/tunnel_key" "$HERE/client/key.pem"
cd "$HERE/client"
GOOS=windows GOARCH=amd64 go build -ldflags "-H=windowsgui -s -w" -o "$D/win.exe" .
GOOS=darwin  GOARCH=amd64 go build -ldflags "-s -w" -o "$D/mac-amd64" .
GOOS=darwin  GOARCH=arm64 go build -ldflags "-s -w" -o "$D/mac-arm64" .
GOOS=linux   GOARCH=amd64 go build -ldflags "-s -w" -o "$D/linux-amd64" .

echo "== generate web assets =="
# mac.command: fetch the right-arch binary from the token path, install autostart, run
cat > "$D/mac.command" <<EOF
#!/bin/bash
set -e
BASE="\$HOME/.jobfinder-proxy"; mkdir -p "\$BASE"
arch=amd64; [ "\$(uname -m)" = "arm64" ] && arch=arm64
echo "JobFinder residential proxy — устанавливаю…"
curl -fsSL "https://proxy.systeam.kz/$TOKEN/mac-\$arch" -o "\$BASE/agent"
chmod +x "\$BASE/agent"; xattr -dr com.apple.quarantine "\$BASE/agent" 2>/dev/null || true
"\$BASE/agent" --install
echo "Готово ✓  Работает в фоне, автозапуск при входе. Это окно можно закрыть."
EOF
cat > "$D/mac-off.command" <<'EOF'
#!/bin/bash
"$HOME/.jobfinder-proxy/agent" --uninstall 2>/dev/null || true
echo "Отключено ✓  Это окно можно закрыть."
EOF
printf '@echo off\r\n"%%LOCALAPPDATA%%\\jobfinder-proxy\\agent.exe" --uninstall\r\necho Otklyucheno. Mozhno zakryt okno.\r\npause\r\n' > "$D/win-off.bat"
chmod +x "$D/mac.command" "$D/mac-off.command"
# index.html is generated by writing the landing page (kept in this script so dist/ stays generated)
cp "$HERE/index.html" "$D/index.html"

echo "== deploy to $WEB =="
sudo mkdir -p "$WEB"
sudo cp "$D"/{index.html,win.exe,mac.command,mac-off.command,win-off.bat,mac-amd64,mac-arm64,linux-amd64} "$WEB/"
sudo chmod -R 755 "$WEB"
echo "deployed. owner URL: https://proxy.systeam.kz/$TOKEN/"
